# Generated by Django 6.0.3 on 2026-06-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20260624_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemaillog',
            name='status',
            field=models.CharField(default='Sent', max_length=255),
        ),
    ]
