# Generated by Django 6.0.3 on 2026-06-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, help_text='Optional question image', null=True, upload_to='question_images/')),
                ('question_type', models.CharField(choices=[('single_select', 'Single Select (Radio Buttons)'), ('multi_select', 'Multi Select (Checkboxes)')], default='single_select', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order of this question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('score', models.FloatField(default=0.0, help_text='Score weight/points for selecting this option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests.question')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=600, help_text='Duration of this section in seconds')),
                ('order', models.IntegerField(default=0, help_text='Display order of this section')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.section'),
        ),
    ]
