# Generated by Django 6.0.3 on 2026-06-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='duration_minutes',
            field=models.IntegerField(default=10, help_text='Duration minutes part'),
        ),
        migrations.AlterField(
            model_name='section',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Duration seconds part'),
        ),
    ]
