# Generated by Django 4.2.23 on 2026-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20260624_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.FileField(blank=True, help_text='Optional choice image', null=True, upload_to='option_images/'),
        ),
    ]
